/*
 * API Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Beer;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BeersApi
 */
@Ignore
public class BeersApiTest {

    private final BeersApi api = new BeersApi();

    
    /**
     * 
     *
     * returns a list of beers
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listBeersV1Test() throws ApiException {
        Integer pageNumber = null;
        Integer pageSize = null;
        List<Beer> response = api.listBeersV1(pageNumber, pageSize);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Delete beer, it was bad
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v2BeersBeerIdDeleteTest() throws ApiException {
        UUID beerId = null;
        api.v2BeersBeerIdDelete(beerId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v2BeersBeerIdGetTest() throws ApiException {
        UUID beerId = null;
        Beer response = api.v2BeersBeerIdGet(beerId);

        // TODO: test validations
    }
    
    /**
     * Update the beer
     *
     * Updating the beer
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v2BeersBeerIdPutTest() throws ApiException {
        UUID beerId = null;
        Beer beer = null;
        api.v2BeersBeerIdPut(beerId, beer);

        // TODO: test validations
    }
    
    /**
     * It&#39;s time to introduce a new beer
     *
     * Create a new tasty Beer
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v3CreateBeerPostTest() throws ApiException {
        Beer beer = null;
        api.v3CreateBeerPost(beer);

        // TODO: test validations
    }
    
}
