/*
 * API Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.BeerOrder;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BeerOrderingServiceApi
 */
@Ignore
public class BeerOrderingServiceApiTest {

    private final BeerOrderingServiceApi api = new BeerOrderingServiceApi();

    
    /**
     * 
     *
     * Place order
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v4CustomersCustomerIdOrdersPostTest() throws ApiException {
        UUID customer = null;
        BeerOrder beerOrder = null;
        api.v4CustomersCustomerIdOrdersPost(customer, beerOrder);

        // TODO: test validations
    }
    
}
