/*
 * API Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Customer;
import org.openapitools.client.model.CustomerPagedList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CustomersApi
 */
@Ignore
public class CustomersApiTest {

    private final CustomersApi api = new CustomersApi();

    
    /**
     * List of customers
     *
     * List of customers in the system which is pageable and will be something else &gt; more things to know 1. hello 2. else 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v3CustomersGetTest() throws ApiException {
        Integer pageNumber = null;
        Integer pageSize = null;
        CustomerPagedList response = api.v3CustomersGet(pageNumber, pageSize);

        // TODO: test validations
    }
    
    /**
     * Creating A new Customer
     *
     * When creating a new Customer the following needs to be true: 1. Customer needs name and address 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v4CustomersPostTest() throws ApiException {
        Customer customer = null;
        api.v4CustomersPost(customer);

        // TODO: test validations
    }
    
}
