/*
 * API Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.BeerOrderLine;

/**
 * BeerOrder
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-30T12:41:59.174138Z[Etc/UTC]")
public class BeerOrder {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_CUSTOMER_ID = "customerId";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_ID)
  private UUID customerId;

  public static final String SERIALIZED_NAME_CUSTOMER_REF = "customerRef";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_REF)
  private String customerRef;

  public static final String SERIALIZED_NAME_BEER_ORDER_LINES = "beerOrderLines";
  @SerializedName(SERIALIZED_NAME_BEER_ORDER_LINES)
  private List<BeerOrderLine> beerOrderLines = null;

  public static final String SERIALIZED_NAME_ORDER_STATUS_CALLBACK_URL = "orderStatusCallbackUrl";
  @SerializedName(SERIALIZED_NAME_ORDER_STATUS_CALLBACK_URL)
  private URI orderStatusCallbackUrl;


   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UUID getId() {
    return id;
  }




  public BeerOrder customerId(UUID customerId) {
    
    this.customerId = customerId;
    return this;
  }

   /**
   * Get customerId
   * @return customerId
  **/
  @ApiModelProperty(required = true, value = "")

  public UUID getCustomerId() {
    return customerId;
  }


  public void setCustomerId(UUID customerId) {
    this.customerId = customerId;
  }


  public BeerOrder customerRef(String customerRef) {
    
    this.customerRef = customerRef;
    return this;
  }

   /**
   * Get customerRef
   * @return customerRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCustomerRef() {
    return customerRef;
  }


  public void setCustomerRef(String customerRef) {
    this.customerRef = customerRef;
  }


  public BeerOrder beerOrderLines(List<BeerOrderLine> beerOrderLines) {
    
    this.beerOrderLines = beerOrderLines;
    return this;
  }

  public BeerOrder addBeerOrderLinesItem(BeerOrderLine beerOrderLinesItem) {
    if (this.beerOrderLines == null) {
      this.beerOrderLines = new ArrayList<BeerOrderLine>();
    }
    this.beerOrderLines.add(beerOrderLinesItem);
    return this;
  }

   /**
   * Get beerOrderLines
   * @return beerOrderLines
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<BeerOrderLine> getBeerOrderLines() {
    return beerOrderLines;
  }


  public void setBeerOrderLines(List<BeerOrderLine> beerOrderLines) {
    this.beerOrderLines = beerOrderLines;
  }


  public BeerOrder orderStatusCallbackUrl(URI orderStatusCallbackUrl) {
    
    this.orderStatusCallbackUrl = orderStatusCallbackUrl;
    return this;
  }

   /**
   * Get orderStatusCallbackUrl
   * @return orderStatusCallbackUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public URI getOrderStatusCallbackUrl() {
    return orderStatusCallbackUrl;
  }


  public void setOrderStatusCallbackUrl(URI orderStatusCallbackUrl) {
    this.orderStatusCallbackUrl = orderStatusCallbackUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BeerOrder beerOrder = (BeerOrder) o;
    return Objects.equals(this.id, beerOrder.id) &&
        Objects.equals(this.customerId, beerOrder.customerId) &&
        Objects.equals(this.customerRef, beerOrder.customerRef) &&
        Objects.equals(this.beerOrderLines, beerOrder.beerOrderLines) &&
        Objects.equals(this.orderStatusCallbackUrl, beerOrder.orderStatusCallbackUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, customerId, customerRef, beerOrderLines, orderStatusCallbackUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BeerOrder {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    customerRef: ").append(toIndentedString(customerRef)).append("\n");
    sb.append("    beerOrderLines: ").append(toIndentedString(beerOrderLines)).append("\n");
    sb.append("    orderStatusCallbackUrl: ").append(toIndentedString(orderStatusCallbackUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

