/*
 * API Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.BeerOrderLine;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BeerOrder
 */
public class BeerOrderTest {
    private final BeerOrder model = new BeerOrder();

    /**
     * Model tests for BeerOrder
     */
    @Test
    public void testBeerOrder() {
        // TODO: test BeerOrder
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'customerRef'
     */
    @Test
    public void customerRefTest() {
        // TODO: test customerRef
    }

    /**
     * Test the property 'beerOrderLines'
     */
    @Test
    public void beerOrderLinesTest() {
        // TODO: test beerOrderLines
    }

    /**
     * Test the property 'orderStatusCallbackUrl'
     */
    @Test
    public void orderStatusCallbackUrlTest() {
        // TODO: test orderStatusCallbackUrl
    }

}
