/*
 * API Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.Customer;
import org.openapitools.client.model.PagedResponse;
import org.openapitools.client.model.PagedResponsePageable;
import org.openapitools.client.model.PagedResponsePageableSort;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CustomerPagedList
 */
public class CustomerPagedListTest {
    private final CustomerPagedList model = new CustomerPagedList();

    /**
     * Model tests for CustomerPagedList
     */
    @Test
    public void testCustomerPagedList() {
        // TODO: test CustomerPagedList
    }

    /**
     * Test the property 'pageable'
     */
    @Test
    public void pageableTest() {
        // TODO: test pageable
    }

    /**
     * Test the property 'totalPages'
     */
    @Test
    public void totalPagesTest() {
        // TODO: test totalPages
    }

    /**
     * Test the property 'last'
     */
    @Test
    public void lastTest() {
        // TODO: test last
    }

    /**
     * Test the property 'totalElements'
     */
    @Test
    public void totalElementsTest() {
        // TODO: test totalElements
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'numberOfElements'
     */
    @Test
    public void numberOfElementsTest() {
        // TODO: test numberOfElements
    }

    /**
     * Test the property 'sort'
     */
    @Test
    public void sortTest() {
        // TODO: test sort
    }

    /**
     * Test the property 'first'
     */
    @Test
    public void firstTest() {
        // TODO: test first
    }

}
