/*
 * API Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PagedResponsePageableSort
 */
public class PagedResponsePageableSortTest {
    private final PagedResponsePageableSort model = new PagedResponsePageableSort();

    /**
     * Model tests for PagedResponsePageableSort
     */
    @Test
    public void testPagedResponsePageableSort() {
        // TODO: test PagedResponsePageableSort
    }

    /**
     * Test the property 'sorted'
     */
    @Test
    public void sortedTest() {
        // TODO: test sorted
    }

    /**
     * Test the property 'unsorted'
     */
    @Test
    public void unsortedTest() {
        // TODO: test unsorted
    }

}
